Repository Nargonath/cra-build-watch, pull requests merged in 2020-10, with the labels that each got.

#249 fixed issues related to CRA 4
  README.md
  scripts/index.js
Labels: enhancement

#255 Update node requirement version & update semantic-release version
  package.json
Labels: bug, enhancement

#258 Update webpack-html-plugin & fix travis deploy script
  .travis.yml
  package.json
  yarn.lock
Labels: dependency, semantic-release
